name: Publish Arby Audio 3D to PyPI

on:
  release:
    types: [published]

permissions:
  contents: read

jobs:
  build-and-publish:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.x"

      - name: Install build and Twine
        run: |
          python -m pip install --upgrade pip
          python -m pip install build twine

      - name: Build Arby Audio 3D
        run: |
          python -m build

      - name: Upload build artifacts (optional)
        uses: actions/upload-artifact@v4
        with:
          name: arby-audio3d-dists
          path: dist/

      - name: Publish to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          packages-dir: dist/
