# GitHub Actions Workflow for Arby Audio 3D
# Builds and publishes the package to PyPI when a GitHub Release is published.

name: Publish Arby Audio 3D to PyPI

on:
  release:
    types: [published]

permissions:
  contents: read

jobs:
  build:
    name: Build distribution
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.x"

      - name: Install build dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install build

      - name: Build distributions
        run: |
          python -m build
          
      - name: Upload build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: arby-audio3d-dists
          path: dist/

  publish:
    name: Publish to PyPI
    runs-on: ubuntu-latest
    needs: build
    permissions:
      id-token: write

    environment:
      name: pypi
      url: https://pypi.org/project/arby-audio3d/${{ github.event.release.name }}

    steps:
      - name: Download built distributions
        uses: actions/download-artifact@v4
        with:
          name: arby-audio3d-dists
          path: dist/

      - name: Publish to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          packages-dir: dist/
